version: '3' # composeファイルのバージョン
services:
  app: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - .:/go/src/
    tty: true # コンテナの永続化
    environment:
      - TZ=Asia/Tokyo
      - "GOPATH=/go"
    ports:
      - 8080:8080